### PR TITLE
fix: Stop double focus of button group

### LINKED ISSUE #43: ButtonGroup double focus
## Expectations

A `<ButtonGroup>` should never allow focus on more than one item.

## Reality

With some amount of effort, you can break focus styling for buttons.

## Steps to Reproduce

1. Mouse down on the last button within a `<ButtonGroup>`
1. Drag off of the button and then mouse up
1. Switch to a new tab and then return

Result: both the first and last button will style with a focus state.

double-focus

###### Fine Print

* Component: 
* Browsers: all

### PR DESCRIPTION
**Pull request by ryanseddon**
## Description

Stop browser double focusing the buttons in side a `<ButtonGroup />` when following the reproduction steps in #43.

~~Not sure on my solution and this hasn't got tests yet but wanted to put it up and see what you think.~~

## Detail
buttongroup-focus

closes #43 

## Checklist

* [ ] :ok_hand: design updates are Garden Designer approved (add the
      designer as a reviewer)
* [ ] :nail_care: view component styling is based on a Garden CSS
  component
* [ ] :globe_with_meridians: Styleguidist demo is up-to-date (`yarn start`)
* [ ] :arrow_left: renders as expected with reversed (RTL) direction
* [ ] :guardsman: includes new unit and snapshot tests
* [ ] :ledger: any new files are included in the packages `src/index.js` export
* [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

File: packages/selection/src/containers/SelectionContainer.js [hunk 1]
```diff
@@ -206,8 +212,14 @@ export class SelectionContainer extends ControlledComponent {
...
           if (typeof focusedKey === 'undefined') {
             let selectedIndex = this.keyIndexMap[this.getControlledState().selectedKey];
-
-            if (typeof selectedIndex === 'undefined') {
+            const activeElement = document.activeElement;
+            const activeElementIndex = [...activeElement.parentNode.children].indexOf(
+              activeElement
+            );
+
+            if (activeElement !== -1) {
```
Comment (austin94) [inline packages/selection/src/containers/SelectionContainer.js]: Should you be comparing `activeElementIndex` here instead?

File: packages/selection/src/containers/SelectionContainer.js [hunk 2]
```diff
@@ -169,6 +169,12 @@ export class SelectionContainer extends ControlledComponent {
 
   onFocusSelectionModelChange = ({ newSelection }) => {
     const focusedKey = this.indexKeyMap[newSelection];
+    const activeElement = document.activeElement;
```
Comment (austin94) [inline packages/selection/src/containers/SelectionContainer.js]: Could we use the `activeElement` `dom-helper` utility here for cross-browser support? https://www.npmjs.com/package/dom-helpers

This helps cover the weird use-cases in IE11 with returning from another tab (probably some other things as well).

**Comment by ryanseddon** [comment]
> this hasn't got tests yet but wanted to put it up and see what you think.

Was planning on doing tests today, just wanted feedback on the approach and if you can think of a better way to do it?

File: packages/selection/src/containers/SelectionContainer.js [hunk 3]
```diff
@@ -169,6 +169,12 @@ export class SelectionContainer extends ControlledComponent {
...
+    const browserSelectionIndex = [...activeElement.parentNode.children].indexOf(activeElement);
```
Comment (austin94) [inline packages/selection/src/containers/SelectionContainer.js]: Another thing I just thought of is that this has the assumption that all "selectable" items are children of the parentNode. This isn't always the case. Since you can spread these render-props to a variety of areas it may or may not be in the correct placement.

**Comment by austin94** [comment]
After looking through this some more, I think this would solve the ButtonGroup example, but would fail in areas that don't have selectable items that are direct siblings of each other.

I'm also not seeing this occur in Firefox. Or in components that are not ButtonGroup in the other browsers.  https://garden.zendesk.com/react-components/tabs/#!/Tabs/1 is working for example.

Could you look into if it's just a focus issue since these components are using `<buttons>` internally and are able to grab focus?

**Comment by ryanseddon** [comment]
This is working as expected now across all components that utilise SelectionContainer.

The spec around activeElement focus is fairly ambiguous so I think browser vendors interpret it differently to each other.

**Comment by ryanseddon** [comment]
So after some internal discussion we've agreed that this isn't the right approach, will keep this open and push the change when I have it.

**Comment by ryanseddon** [comment]
@austin94 I added a test to cover this code, I did however look at the dom properties instead as enzyme's `simulate()` doesn't trigger a render. If there's a better way let me know.

File: packages/buttons/src/containers/ButtonGroupContainer.spec.js [hunk 4]
```diff
@@ -76,5 +76,15 @@ describe('ButtonGroupContainer', () => {
         expect(button).toHaveProp('tabIndex', -1);
       });
     });
+
+    it('moves focus to the ButtonGroupView if a button receives focus', () => {
```
Comment (austin94) [inline packages/buttons/src/containers/ButtonGroupContainer.spec.js]: Active element detection is hard to test within Enzyme 😢 

A common approach that I use is to only mock the expected functionality. The `onFocus` composition that we have on each button is only calling `target.parentNode.focus()`. How focus is handled after that point is a browser concern and not really something that is "testable", especially with jsdom.  I suggest just ensuring that we call the correct method with a mock and calling it a day.

An example is:

```
it('moves focus to the ButtonGroupView if a button receives focus', () => {
      const focusMock = jest.fn();

      findButtons(wrapper)
        .at(0)
        .simulate('focus', { target: { parentNode: { focus: focusMock } } });

      expect(focusMock).toHaveBeenCalled();
    });
```

Comment (ryanseddon) [reply packages/buttons/src/containers/ButtonGroupContainer.spec.js]: ok that makes sense, will do that 👍

**Comment by ryanseddon** [comment]
> Didnt realize that dom-helpers had that utility!

Me either, it's not documented either. I was originally using `Element#closest` which works in all browsers but IE11 so did a search on the dom-helpers codebase.
