### PR TITLE
fix(tabs): prevent `isVertical` styling cascade

### LINKED ISSUE #1817: Nested Tabs isVertical inherit
## Expectations
I nest a horizontal tab inside a vertical tab and the layout remains as shown on the demo page.

## Reality
If a parent Tabs has isVertical, all other nested instances of Tabs will inherit it even if it is not there or is false.

## Steps to Reproduce
Here's the [sandbox](https://codesandbox.io/p/devbox/zendesk-tabs-8dcvcq?file=%2Fapp%2Fpage.tsx%3A4%2C60) to recreate it.

1. click on first vertical tab

### Fine Print

- Component: Tabs
- Version: react-tabs 8.76.2
- Browsers: all

### PR DESCRIPTION
**Pull request by jzempel**
## Description

The previous `verticalStyling` catch-all function in `StyledTabs` was not well-structured, allowing component CSS to leak into child `Tabs` so that if any parent sets the `isVertical` prop, all children would be vertically styled regardless of their `isVertical` prop setting.

This PR eradicates the `verticalStyling` function by portioning all of its properties out to relevant components, conditionally and precisely applying CSS depending on the context. The updated styles follow Garden's [API rules](https://github.com/zendeskgarden/react-components/blob/main/docs/api.md#rules) by utilizing `sizeStyles` and `colorStyles` accordingly.

## Detail

closes #1817 

## Checklist

- [ ] :ok_hand: ~design updates will be Garden Designer approved (add the designer as a reviewer)~
- [x] :globe_with_meridians: demo is up-to-date (`npm start`)
- [x] :arrow_left: renders as expected with reversed (RTL) direction
- [x] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [ ] :guardsman: ~includes new unit tests. Maintain existing coverage (always >= 96%)~
- [ ] :wheelchair: ~tested for WCAG 2.1 AA accessibility compliance~
- [ ] :memo: ~tested in Chrome, Firefox, Safari, and Edge~

### CODE REVIEW

File: packages/tabs/src/styled/StyledTabs.ts [hunk 1]
```diff
@@ -5,78 +5,26 @@
...
-
 /**
  * Accepts all `<div>` props
  */
 export const StyledTabs = styled.div.attrs<IStyledTabsProps>({
   'data-garden-id': COMPONENT_ID,
   'data-garden-version': PACKAGE_VERSION
 })<IStyledTabsProps>`
-  display: block;
+  display: ${props => (props.isVertical ? 'table' : 'block')};
```
Comment (geotrev) [inline packages/tabs/src/styled/StyledTabs.ts:24]: I'm wondeirng if using flex might be preferable for handling flow. 🤔 `display: table` can impact the element's role for some screen readers ([source](https://www.456bereastreet.com/archive/201110/using_displaytable_has_semantic_effects_in_some_screen_readers/)). Granted, it's a small subset of SRs, so maybe not a huge deal?

**Review by geotrev — COMMENTED** [review]
Looks good. Just the one comment.

One unrelated thing I noticed (present on `main`): trying to use arrow keys backward through tabs requires one extra arrow key press to loop from the first to last tab. Guessing that's in the tabs container logic though. We can track that separately but not sure if anyone else noticed.

File: packages/tabs/src/styled/StyledTabs.ts (hunk 1 above)
Comment (geotrev) [reply packages/tabs/src/styled/StyledTabs.ts:24]: I also confirmed using a fake table demo in the link above that Chrome + JAWS treats CSS tables as actual tables (so long as they have more than one cell). 😬

Comment (jzempel) [reply packages/tabs/src/styled/StyledTabs.ts:24]: @geotrev all valid concerns for sure. For this PR I want to retain exact parity with the previous styling, since that's already been through a11y audit.

> trying to use arrow keys backward through tabs requires one extra arrow key press to loop from the first to last tab

Looks like that might be related to the inclusion of a `disabled` tab in the Storybook example. Again, let's plan to address under a separate effort.

**Review by geotrev — APPROVED** [review]
