### PR TITLE
fix(dropdowns): add missing data-garden- attributes to menu item icon elements

### LINKED ISSUE #1128: Missing data-garden-id on Menu Item Icon
https://github.com/zendeskgarden/react-components/blob/d4fd7bc1cd62ce5107f8464b00fbec197d96d673/packages/dropdowns/src/elements/Menu/Items/Item.tsx#L95

Is it possible to add a `data-garden-id` to the Icon for a selected menu item so it can be targeted by css selector outside?? In previous garden versions where these were inserted via a pseduo selector they could easily be found, but in the new setup without a `data-garden-id` on the `StyledItemIcon` its quite a pain.

### PR DESCRIPTION
**Pull request by jzempel**
## Description

Add missing `data-garden-[id/version]` attributes to `StyledItemIcon` components.

## Detail

Closes #1128

## Checklist

- [ ] :ok_hand: ~design updates are Garden Designer approved (add the
      designer as a reviewer)~
- [x] :globe_with_meridians: demo is up-to-date (`yarn start`)
- [ ] :arrow_left: ~renders as expected with reversed (RTL) direction~
- [ ] :metal: ~renders as expected with Bedrock CSS (`?bedrock`)~
- [ ] :wheelchair: ~analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~
- [ ] :guardsman: ~includes new unit tests~
- [ ] :memo: ~tested in Chrome, Firefox, Safari, Edge, and IE11~

### CODE REVIEW

File: packages/dropdowns/stories/examples/Menu/Advanced.tsx [hunk 1]
```diff
@@ -46,29 +46,22 @@ interface IStoryProps {
...
         <Col textAlign="center">
-          <Dropdown
-            isOpen={isOpen}
-            onStateChange={changes => {
-              if (Object.prototype.hasOwnProperty.call(changes, 'isOpen')) {
-                setIsOpen(changes.isOpen === true);
-              }
-            }}
-          >
+          <Dropdown isOpen={isOpen || undefined}>
```
Comment (jzempel) [inline packages/dropdowns/stories/examples/Menu/Advanced.tsx:64]: I realize this treatment flips the component between controlled and uncontrolled (and results in a warning). But that the point – the control demonstrates both uses. More importantly, we have the ability to observe and use dev tools to debug the menu items which is imperative for the storybook demo.

Comment (hzhu) [reply packages/dropdowns/stories/examples/Menu/Advanced.tsx:64]: I think a more suitable structure would be to demonstrate one of each usage per story — similar to the [accordion](https://zendeskgarden.github.io/react-components/?path=/story/components-accordions-accordion--uncontrolled) stories. Probably not the right time for re-structuring, but just wanted to throw the idea out there.

**Review by hzhu — APPROVED** [review]

File: packages/dropdowns/stories/examples/Menu/Advanced.tsx (hunk 1 above)
Comment (jzempel) [reply packages/dropdowns/stories/examples/Menu/Advanced.tsx:64]: Perhaps. This directly copies the `Default` dropdowns story. So we may want to address both.
