### PR TITLE
fix(accordions): Stop stepper's counter incrementing twice in React.StrictMode

### LINKED ISSUE #849: Stepper not rendering properly in React.StrictMode
## Expectations
Stepper's label will start from 1 and increment by 1 as shown below:
 
image

## Reality
Stepper's label starts from 2 and incremented by 2.

image

## Steps to Reproduce

1. Create an app using Create React App
2. Install `@zendeskgarden/react-theming` and `@zendeskgarden/react-accordions`
3. Use the example of `Stepper` from https://zendeskgarden.github.io/react-components/accordions/ 

## Example 
https://codesandbox.io/s/zendesk-garden-stepper-w5ujw

### PR DESCRIPTION
**Pull request by MarkSFrancis**
## Description

In [React.StrictMode](https://reactjs.org/docs/strict-mode.html), components are rendered twice. This causes the `Label` in the `Stepper` to go up in twos (e.g. step 2, 4, 6  instead of 1, 2, 3), which is undesired behaviour.

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:
> 
> * Class component constructor, render, and shouldComponentUpdate methods
> * Class component static getDerivedStateFromProps method
> * Function component bodies
> * State updater functions (the first argument to setState)
> * Functions passed to useState, useMemo, or useReducer

## Detail

This change uses useEffect to increment/ decrement the value as the component is unmounted/ remounted, fixing the issue of double-rendering components. 

Tests have been added which prove that the change is backwards compatible, but also fixes the issue. These tests will not pass in the older version.

Closes #849

## Checklist

Not sure which of the checklist apply - please can someone confirm?

- [ ] ~:ok_hand: design updates are Garden Designer approved (add the
      designer as a reviewer)~
- [ ] ~:globe_with_meridians: demo is up-to-date (`yarn start`)~
- [ ] ~:arrow_left: renders as expected with reversed (RTL) direction~
- [ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)
- [ ] ~:wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~
- [x] :guardsman: includes new unit tests
- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

File: packages/accordions/src/elements/stepper/components/Step.tsx [hunk 1]
```diff
@@ -5,19 +5,42 @@
...
-  const { currentIndexRef, isHorizontal } = useStepperContext();
-  const stepIndexRef = useRef(currentIndexRef.current++);
-  const stepContextValue = { currentStepIndex: stepIndexRef.current };
+  const [currentStepIndex, context] = useStep();
 
   return (
-    <StepContext.Provider value={stepContextValue}>
-      <StyledStep ref={ref} isHorizontal={isHorizontal} {...props}>
-        {isHorizontal && <StyledLine data-test-id="step-line" />}
+    <StepContext.Provider value={{ currentStepIndex }}>
```
Comment (jzempel) [inline packages/accordions/src/elements/stepper/components/Step.tsx:41]: @hzhu in the (near) future, I'd like for us to find our way to a pure CSS solution to this problem. Reference: https://github.com/zendeskgarden/react-components/blob/ceb91ac0ee5f38192bb66cf3f999bc3031aaa985/packages/typography/src/styled/StyledCodeBlockLine.ts#L24-L25

File: packages/accordions/src/elements/stepper/components/Step.spec.tsx [hunk 2]
```diff
@@ -46,4 +46,38 @@ describe('Step', () => {
 
     expect(queryAllByTestId('step-line')).toHaveLength(0);
   });
+
+  it('does not change step number when running outside strict mode', async () => {
```
Comment (austingreendev) [inline packages/accordions/src/elements/stepper/components/Step.spec.tsx:50]: I think these tests are accurate, but should we also be asserting that the steps are in the correct order as well?

File: packages/accordions/src/elements/stepper/components/Step.tsx [hunk 3]
```diff
@@ -5,19 +5,34 @@
  * found at http://www.apache.org/licenses/LICENSE-2.0.
  */
 
-import React, { forwardRef, useRef, LiHTMLAttributes } from 'react';
+import React, { forwardRef, LiHTMLAttributes, useEffect, useState } from 'react';
 import { StyledStep, StyledLine } from '../../../styled';
 import { StepContext, useStepperContext } from '../../../utils';
 
+const useStep = () => {
```
Comment (austingreendev) [inline packages/accordions/src/elements/stepper/components/Step.tsx:12]: Even though this abstraction is helpful; if we aren't using this hook multiple places it might make more sense to have the logic live within `<Step />` directly. This also would require returning the remaining `context` values as they aren't involved in the step calculation.

File: packages/accordions/src/elements/stepper/components/Step.tsx [hunk 4]
```diff
@@ -5,19 +5,34 @@
...
+  const { currentIndexRef, ...context } = useStepperContext();
+  const [index, setIndex] = useState(currentIndexRef.current);
+
+  useEffect(() => {
+    setIndex(currentIndexRef.current);
+    currentIndexRef.current++;
+    const currentIndex = currentIndexRef;
+
+    return () => {
+      currentIndex.current--;
```
Comment (austingreendev) [inline packages/accordions/src/elements/stepper/components/Step.tsx:22]: Is this decrement effect cleanup necessary? The `currentIndexRef` is set to zero whenever the parent `<Stepper />` is rendered.

File: packages/accordions/src/elements/stepper/components/Step.tsx (hunk 1 above)
Comment (austingreendev) [reply packages/accordions/src/elements/stepper/components/Step.tsx:33]: The CSS solution would help with the visible step name, but we also have to track it for the `activeIndex` styling in controlled modes.

File: packages/accordions/src/elements/stepper/components/Step.tsx (hunk 4 above)
Comment (MarkSFrancis) [reply packages/accordions/src/elements/stepper/components/Step.tsx:22]: Sometimes this is re-rendered when the parent component is not re-rendered. This is what StrictMode does. It'll render these child components twice without rendering `<Stepper />`

File: packages/accordions/src/elements/stepper/components/Step.tsx (hunk 3 above)
Comment (MarkSFrancis) [reply packages/accordions/src/elements/stepper/components/Step.tsx:12]: Happy to change this

File: packages/accordions/src/elements/stepper/components/Step.tsx (hunk 4 above)
Comment (austingreendev) [reply packages/accordions/src/elements/stepper/components/Step.tsx:22]: 👍  Thanks for the explanation

File: packages/accordions/src/elements/stepper/components/Step.tsx (hunk 3 above)
Comment (austingreendev) [reply packages/accordions/src/elements/stepper/components/Step.tsx:12]: Let's bring this logic back into the component. Overall the logic looks good to me.

File: packages/accordions/src/elements/stepper/components/Step.spec.tsx (hunk 2 above)
Comment (MarkSFrancis) [reply packages/accordions/src/elements/stepper/components/Step.spec.tsx:50]: I'm not sure what the best way to do this is, so I've used `findAllByText`, and then asserted the order of elements in the array

Comment (austingreendev) [reply packages/accordions/src/elements/stepper/components/Step.spec.tsx:50]: LGTM 👍

**Review by austingreendev — APPROVED** [review]
Looks good to me! Thanks for taking the time to tweak this @MarkSFrancis

**Review by hzhu — APPROVED** [review]
Thanks @MarkSFrancis! Once the snapshots are updated and the build is passing, this PR can be merged.

**Comment by austingreendev** [comment]
Thanks for the help with this @MarkSFrancis. This will get published during our weekly release next week.
