### PR TITLE
fix(typography): improve fallback handling for invalid `CodeBlock` language

### LINKED ISSUE #1217: Mobile language syntax highlighting
After doing some digging in the [developer-docs repo](https://github.com/zendesk/developer-docs), 
I realized the documentation is getting syntax highlighting through this repo's use of the [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer/) plugin. After looking at the [supported languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js), it seems like they don't support languages used by our mobile integrators.

## Expectations

I expected code snippet syntax highlighting to support common mobile development languages like `java`/`kotlin`/`swift`.

## Reality

Code snippet syntax highlighting doesn't support common mobile development languages.

## Steps to Reproduce

1. Visit some [public mobile documentation](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/sdks/ios/advanced_integration/)
1. Observe lack of syntax highlighting. 

Note: Ignore the fact objective-c snippets aren't being highlighted, this is down to typos in the language keyword after the 3 back-ticks.

Hint to a solution 
There is an [FAQ](https://github.com/FormidableLabs/prism-react-renderer#faq) on the repo's README. 
This sections states how one could add these languages to Prism, in order for them to be picked up.

I've put up a [PR on the repo](https://github.com/FormidableLabs/prism-react-renderer/pull/131), to add these languages to the default list, but it might be rejected.

### Fine Print

- Component: CodeBlock ?
- Version: latest? 🤔 
- Browsers: all

### PR DESCRIPTION
**Pull request by jzempel**
## Description

Updates the `language` prop to fall back to `'tsx'` if an unsupported language is provided. Testing shows that, as a superset of c-like + javascript + JSX + typescript Prism tokenization, `language-tsx` currently seems to provide decent highlighting for languages such as Swift or Kotlin.

## Detail

Resolves #1217 

## Checklist

- [ ] :ok_hand: ~design updates are Garden Designer approved (add the
      designer as a reviewer)~
- [ ] :globe_with_meridians: ~demo is up-to-date (`yarn start`)~
- [ ] :arrow_left: ~renders as expected with reversed (RTL) direction~
- [ ] :metal: ~renders as expected with Bedrock CSS (`?bedrock`)~
- [ ] :wheelchair: ~analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~
- [x] :guardsman: includes new unit tests
- [ ] :memo: ~tested in Chrome, Firefox, Safari, Edge, and IE11~

### CODE REVIEW

File: packages/typography/src/elements/CodeBlock.tsx [hunk 1]
```diff
@@ -24,9 +24,45 @@ interface IToken {
...
+  'tsx',
+  'typescript',
+  'wasm',
+  'yaml'
+] as const;
+
 export interface ICodeBlockProps extends HTMLAttributes<HTMLPreElement> {
   /** Selects the language used by the [Prism](https://prismjs.com/) tokenizer */
-  language?: Language;
+  language?: typeof LANGUAGES[number];
```
Comment (jzempel) [inline packages/typography/src/elements/CodeBlock.tsx:65]: Along with aligning to the specified array, this construct has the affect of improving API output for https://garden.zendesk.com/components/code-block#codeblock.

**Review by KillianSmith0 — COMMENTED** [review]
🚀

**Review by Francois-Esquire — APPROVED** [review]

**Review by hzhu — APPROVED** [review]
